### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by alu0100697032** [alu0100697032/adpr_express_generator#3]

**Comment by alu0100837353** [comment]
Update of README, only waiting to change some link.

**Comment by alu0100837353** [comment]
A small fix. 1a3e0bd9caf573f9e497fdcf7e4204e0335e8df0

**Comment by alu0100837353** [comment]
Last update fixing the obsolete links. 461ed7b14134a9b24476e0098e4ea1c279c0354d
