### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by alu0100697032** [alu0100697032/adpr_express_generator#7]

**Comment by alu0100837353** [comment]
Creating folder tests and files.

**Comment by alu0100837353** [comment]
Added dev dependencies on package.json 08604d774fc042130378f23346c3cd3a6e91c35d

**Comment by alu0100837353** [comment]
Added necesarie files to run tets in a html file. 10e5ce6828dea1794496d8a859866586f354d5ae

**Comment by alu0100837353** [comment]
Test working fine. 2b0f19b1da878215174f1b338e895a8871a721d7

**Comment by alu0100837353** [comment]
Added lastest test 17cdaa3072eaccfb2b66039f6ca1da7f08cdb547
